In [1]:
import numpy as np
import pandas as pd

In [20]:
class SVM():

  def __init__(self,learningRate,no_of_iterations,lambda_reg):
      self.learningRate=learningRate
      self.no_of_iterations=no_of_iterations
      self.lambda_reg=lambda_reg

  def fit(self,X,Y):
    self.m,self.n=X.shape
    self.w=np.zeros(self.n)
    self.b=0
    self.X=X
    self.Y=Y

    for i in range(self.no_of_iterations):
         self.update_weights()
  def update_weights(self):

      #label encoding
      y_label=np.where(self.Y<=0 , -1,1)
      for index, x_i in enumerate(self.X):

              condition = y_label[index] * (np.dot(x_i, self.w) - self.b) >= 1

              if (condition == True):

                dw = 2 * self.lambda_reg * self.w
                db = 0

              else:

                dw = 2 * self.lambda_reg * self.w - np.dot(x_i, y_label[index])
                db = y_label[index]


              self.w = self.w - self.learningRate * dw

              self.b = self.b - self.learningRate * db

  def predict(self, X):

    output = np.dot(X, self.w) - self.b
    
    predicted_labels = np.sign(output) #wherever its less than -1, value will become -1 and more than 1 becomes 1

    y_hat = np.where(predicted_labels <= -1, 0, 1) #reverting -1,1 to 0,1

    return y_hat

In [3]:
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [4]:
diabetes_data=pd.read_csv("/content/diabetes.csv")
diabetes_data.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [6]:
diabetes_data.shape

(768, 9)

In [7]:
diabetes_data.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [8]:
input=diabetes_data.drop(columns="Outcome",axis=1)
outcome=diabetes_data["Outcome"]
input.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148,72,35,0,33.6,0.627,50
1,1,85,66,29,0,26.6,0.351,31
2,8,183,64,0,0,23.3,0.672,32
3,1,89,66,23,94,28.1,0.167,21
4,0,137,40,35,168,43.1,2.288,33

In [9]:
scalar=StandardScaler()
scalar.fit(input)
standard_data=scalar.transform(input)

In [10]:
print(standard_data)

[[ 0.63994726  0.84832379  0.14964075 ...  0.20401277  0.46849198
   1.4259954 ]
 [-0.84488505 -1.12339636 -0.16054575 ... -0.68442195 -0.36506078
  -0.19067191]
 [ 1.23388019  1.94372388 -0.26394125 ... -1.10325546  0.60439732
  -0.10558415]
 ...
 [ 0.3429808   0.00330087  0.14964075 ... -0.73518964 -0.68519336
  -0.27575966]
 [-0.84488505  0.1597866  -0.47073225 ... -0.24020459 -0.37110101
   1.17073215]
 [-0.84488505 -0.8730192   0.04624525 ... -0.20212881 -0.47378505
  -0.87137393]]

In [11]:
features=standard_data

In [12]:
X_train,X_test,Y_train,Y_test=train_test_split(features,outcome,test_size=0.2,random_state=2)

In [29]:
model=SVM(0.001,1000,0.1)

In [30]:
model.fit(X_train,Y_train)

In [31]:
modelResults=model.predict(X_train)
accuracy=accuracy_score(Y_train,modelResults)
print(accuracy)

0.7801302931596091

In [32]:
modelResults=model.predict(X_test)
accuracy=accuracy_score(Y_test,modelResults)
print(accuracy)

0.7727272727272727

In [36]:
input_data = (5,166,72,19,175,25.8,0.587,51)

# change the input data to numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the array
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

# standardizing the input data
std_data = scalar.transform(input_data_reshaped)
#print(std_data)

prediction = model.predict(std_data)
#print(prediction)

if (prediction[0] == 0):
  print('The person is not diabetic')

else:
  print('The Person is diabetic')

The Person is diabetic

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(